---
title: "COVID-19 Wastewater Analysis"
author: "Lipp Laboratory, Department of Environmental Health Science, University of Georgia"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_depth: 3
---


```{r}
library(tidyverse)
library(plotly)
library(ggpubr)
library(stringi)
library(stringr)
```

```{r}
raw_data <- readRDS("./n1_n2_cleaned_cases.rds")
```


```{r}
#can add new calcs here later if needed
final_data <- raw_data %>% mutate(log_copy_per_L = log10(mean_copy_num_L)) %>%
  rename(Facility = wrf) %>%
  mutate(Facility = recode(Facility, 
                           "NO" = "WRF A",
                           "MI" = "WRF B",
                           "CC" = "WRF C"))
```


```{r}
clean_plot <- final_data %>% ggplot() + 
  geom_bar(aes(x = date, y = new_cases_clarke), stat = "sum", alpha = 0.35, fill = "#7570B3", show.legend = FALSE)
  
clean_plot <- clean_plot + 
  geom_line(aes(x = date, y = X10_day_ave_clarke), size = 1, color ="#E6AB02") +           
  geom_point(aes(x = date, y = log_copy_per_L*10, color = target, shape = Facility), size = 2) +
  geom_hline(yintercept = 35.5, linetype = "dashed") +
  annotate("text", x = as.Date("2020-03-20"), y = 39, label = "LOD")

clean_plot <- clean_plot + 
  scale_y_continuous(limits = c(0,100), sec.axis = sec_axis(~. / 10, name = "SARS CoV-2 Log Copies Per L")) +
  ylab("Clarke County Daily Cases") + xlab("Date") + 
  theme_classic() + guides(color=guide_legend("SARS CoV-2 Target")) 

clean_plot <- clean_plot + 
  theme(legend.position = "bottom") 

clean_plot <- clean_plot + scale_color_manual(na.translate = FALSE, values = c("#1B9E77", "#D95F02")) + scale_shape_manual(na.translate = FALSE, values = c(1:2))

clean_plot
```

```{r}
ggsave(filename = "./athens_covid_wastewater_master_plot.png", plot = clean_plot)
```

